### PR TITLE
Children rendering added

### PR DESCRIPTION
**Pull request by indapublic**

### CODE REVIEW

**Review by kennetpostigo — COMMENTED** [review]
LGTM

**Review by kennetpostigo — APPROVED** [review]

**Comment by kennetpostigo** [comment]
@indapublic sorry for the delay publishing to npm. publishing now

**Comment by kennetpostigo** [comment]
children rendering released in 0.7.0

**Comment by indapublic** [comment]
@kennetpostigo Awesome, thanks!

**Pull request merged**
