### PR TITLE
Reset "disabled" state when google snippet is already loaded

### PR DESCRIPTION
**Pull request by koss-lebedev**
Hey @kennetpostigo ,

this is the fix for the problem described in issue #23 . What happens is that we disable button while google API libraries are loading, and re-enable button when they are loaded. But if login component gets unmounted and then mounted again, the google API libraries are already on the page, and the callback that should re-enable button never gets fired. This PR fixes that problem

### CODE REVIEW

**Review by kennetpostigo — APPROVED** [review]

**Comment by kennetpostigo** [comment]
@koss-lebedev would disable ever be true? Should this be a prop?

**Comment by koss-lebedev** [comment]
@kennetpostigo Yes, we can also disable button by passing `disabled={true}` as a prop. So in short:

- while google scripts are loading, button is disabled because `disabled` state is true (`disabled` prop is ignored at that moment)
- when scripts finished loading, `disabled` state changes to false, and now we use `disabled` prop value (which can we true, in which case button will remain disabled)

**Comment by kennetpostigo** [comment]
@koss-lebedev did you mean to close this?

**Comment by koss-lebedev** [comment]
@kennetpostigo Sorry, I closed it by mistake

**Comment by kennetpostigo** [comment]
@koss-lebedev merge when you feel it is ready :)

**Pull request merged**
