### PR TITLE
Release 0.8.0

### PR DESCRIPTION
**Pull request by koss-lebedev**

### CODE REVIEW

**Comment by koss-lebedev** [comment]
hey @kennetpostigo ,

thanks for allowing me to contribute to the project! Yesterday I received invites to manage GitHub repos, but it looks like I cannot merge or publish anything without somebody reviewing PRs :)

BTW, `npm publish` doesn't work too, it fails with "you do not have permission to publish "react-google-login-component"

**Comment by kennetpostigo** [comment]
@koss-lebedev No problem! Did you receive an email or notification from npm to confirm anything? I believe I gave you publishing rights

**Comment by koss-lebedev** [comment]
@kennetpostigo No, I didn't receive any notifications from npm, only from Github.
I actually can see my avatar in the list of contributors (https://www.npmjs.com/package/react-google-login-component), but publish command doesn't work

**Comment by kennetpostigo** [comment]
@koss-lebedev Okay give me a sec, so I can figure out how to give you publishing rights.

**Comment by kennetpostigo** [comment]
@koss-lebedev are you logged into npm when trying to publish? From asking around and googling adding you as a collaborator on npmjs should give you write access

**Comment by koss-lebedev** [comment]
@kennetpostigo Yes, I was logged in, but as a different user 😮  I don't know how it happened, but it looks like I now have one npm account bound to my email (koss.lebedev), and one bound to GitHub account (koss-lebedev). Anyway, I signed in with a different account and it worked. Thank you for helping :)

**Comment by kennetpostigo** [comment]
Awesome @koss-lebedev ! Thank you soo much for helping out!

**Pull request merged**
